// <auto-generated />
using System;
using K12WebApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K12WebApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220309203244_Groceries")]
    partial class Groceries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("K12WebApp.Shared.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroceryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isBought")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Groceries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            DateCreated = new DateTime(2022, 3, 9, 21, 32, 44, 448, DateTimeKind.Local).AddTicks(6734),
                            GroceryName = "Løg",
                            isBought = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            DateCreated = new DateTime(2022, 3, 9, 21, 32, 44, 448, DateTimeKind.Local).AddTicks(6765),
                            GroceryName = "Hvidløg",
                            isBought = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            DateCreated = new DateTime(2022, 3, 9, 21, 32, 44, 448, DateTimeKind.Local).AddTicks(6767),
                            GroceryName = "Affaldsposer",
                            isBought = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = 1,
                            DateCreated = new DateTime(2022, 3, 9, 21, 32, 44, 448, DateTimeKind.Local).AddTicks(6769),
                            GroceryName = "Karry",
                            isBought = false
                        });
                });

            modelBuilder.Entity("K12WebApp.Shared.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Køkken Ansvarlig"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Køkken Beboer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tjanse Tjekker"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Køkken Kasserer"
                        });
                });

            modelBuilder.Entity("K12WebApp.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Christian",
                            LastName = "Merithz Uhrenfeldt Nielsen",
                            NickName = "Krølle",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Joey",
                            LastName = "Knutsson",
                            NickName = "Joey",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Emma",
                            LastName = "Rosa",
                            NickName = "Ems",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Kasper",
                            LastName = "Djælund Nyberg",
                            NickName = "Guffe",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Daniel",
                            LastName = "Katz",
                            NickName = "Danniboi",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Andreas",
                            LastName = "Ven",
                            NickName = "Venno",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Lynge",
                            LastName = "Moustgaard",
                            NickName = "LyngLyng",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Lucas",
                            LastName = "Zacho",
                            NickName = "Peter",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Nicolai",
                            LastName = "Toft",
                            NickName = "Nico",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Anastasia",
                            LastName = "Jakobsen",
                            NickName = "Anastasia",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Eva",
                            LastName = "Sand Larsen",
                            NickName = "Eva",
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("K12WebApp.Shared.Grocery", b =>
                {
                    b.HasOne("K12WebApp.Shared.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("K12WebApp.Shared.User", b =>
                {
                    b.HasOne("K12WebApp.Shared.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
